### ISSUE TITLE
Switching to JSON/YAML for config

### ISSUE THREAD

**Issue by brokkr** [brokkr/poca#128]
I believe either JSON or YAML would allow for significant code simpification (there's a _lot_ of lines just parsing the XML). And I don't believe we really depend on the things that XML brings to the table (namespaces etc.)?

Advantages of JSON: Built-in (one less dependency), fast
Advantages of YAML: Easy to read, supplanting pickle?

Really depends on how well either one deals with the heavily nested structure of say, a subscription with filters and metadata and renames... Also how would attributes translate?

**Comment by brokkr** [comment]
Leaving aside the question of attributes, YAML seems like an easy choice. 

* It's easy to read and write
* Recreating the poca.xml structure is easy
* Parsing it is two lines of code and I have the entire dictionary in hand

Example:
```
defaults:
  metadata:
    genre: podcast
settings:
  base_dir: /mnt/media/
  filenames: permissive
  id3removev1: true
  id3v2version: 3
  useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
subscriptions:
- filters:
    title: natur
  max_number: 2
  metadata:
    artist: Det:Er
  rename:
  - title
  - episode_title
  title: "Er h\xE5bet stadig gr\xF8nt?"
  url: https://www.dr.dk/mu/feed/er-habet-stadig-groent.xml?format=podcast
- filters:
    filename: CCEpSpecial
  max_number: 2
  title: The Crate and Crowbar
  url: http://crateandcrowbar.com/category/episode/feed/

```

A few issues:
* Dictionaries are randomly rearranged. Apparently this can be avoided using `sortkeys=False` when dumping? (https://stackoverflow.com/a/64902048) but it doesn't seem to work ootb with safe_dump.
* yaml dumping is by default encoded ascii where non-ascii characters appear as hex values (i.e. in order to make sense of the text above, you would have to decode it as 'latin-1') Apparently it can dump unicode characters straight into the file and encode it as UTF-8 using the `allow_unicode=True` setting (https://stackoverflow.com/a/29600111) Also works for safe_dump (tested)
* Biggest one: How to validate input? YAML doesn't come with schemas so some options are:
     * Build your own: https://stackoverflow.com/a/45812573
     * Use third party: schema or Cerberus or jsonschema
     * drop validation 
* read up on how safe is safe_load? and if we safe_load does it matter if we don't safe_dump?
